# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: meow meow meow
email: meow@meow.meow
description: > # this means to ignore newlines until "baseurl:"
  meow meow meow meow Meow meow meow meow meow Meow meow meow meow meow meow meow 
  meow meow meow Meow meow meow meow meow meow meow Meow go go
  meow meow meow meow meow Meow 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lamnguyenx.github.io" # the base hostname & protocol for your site
twitter_username: lamnguyenx
github_username:  lamnguyenx

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight