# Preface {.unnumbered}

This is a side-by-side comparison of the [Polars](https://www.pola.rs/)
and [Pandas](https://pandas.pydata.org/) dataframe libraries,
based on [Modern Pandas](https://tomaugspurger.github.io/posts/modern-8-scaling/) by Tom Augsburger.

(In case you haven't heard, Polars is a very fast and elegant dataframe libary that does the same kinds of things Pandas does.)

The bulk of this book is structured examples of idiomatic Polars and Pandas code, with commentary on the API and performance of both.

For the most part, I argue that Polars is "better" than Pandas, though I do try and make it clear when Polars is lacking a Pandas feature or is otherwise disappointing.

## Who is this for?

This is not a beginner's introduction to data programming, though you certainly don't need to be an expert to read it. If you have some familiarity with any dataframe library, most of the examples should make sense, but if you're familiar with Pandas they'll make even more sense because all the Polars code is accompanied by the equivalent Pandas code.

You don't need to have read *Modern Pandas*, though I of course think it's a great read.
